(function(){
  "use strict";
  const $=id=>document.getElementById(id);
  const authView=$("authView"),profileView=$("profileView"),loginForm=$("loginForm"),signupForm=$("signupForm"),forgotForm=$("forgotForm"),loginTab=$("loginTab"),signupTab=$("signupTab"),authMessage=$("authMessage"),forgotMessage=$("forgotMessage"),mobileForm=$("mobileForm"),mobileMessage=$("mobileMessage"),mobileNumber=$("mobileNumber"),mobileSavedBadge=$("mobileSavedBadge");
  let currentUser=null;
  function message(el,text,type){if(!el)return;el.textContent=text||"";el.className="account-message"+(type?" "+type:"")}
  function mode(which){const login=which==="login";loginForm.classList.toggle("is-hidden",!login);signupForm.classList.toggle("is-hidden",login);forgotForm.classList.add("is-hidden");loginTab.classList.toggle("active",login);signupTab.classList.toggle("active",!login);message(authMessage,"");message(forgotMessage,"")}
  function showForgot(){loginForm.classList.add("is-hidden");signupForm.classList.add("is-hidden");forgotForm.classList.remove("is-hidden");loginTab.classList.remove("active");signupTab.classList.remove("active");const loginEmail=loginForm.querySelector('input[name="email"]');const forgotEmail=forgotForm.querySelector('input[name="email"]');if(loginEmail&&forgotEmail&&!forgotEmail.value)forgotEmail.value=loginEmail.value;message(authMessage,"")}
  async function api(path,options){let response;try{response=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options&&options.headers||{})},...options})}catch{throw new Error("Unable to connect to the account service. Please try again.")}let data={};try{data=await response.json()}catch{}if(!response.ok){if(response.status===404)throw new Error("Customer account service is not enabled on the server yet.");throw new Error(data.error||"Something went wrong. Please try again.")}return data}
  function localPhone(value){const digits=String(value||"").replace(/\D/g,"");return digits.length===12&&digits.startsWith("91")?digits.slice(2):digits.length===11&&digits.startsWith("0")?digits.slice(1):digits}
  function providerLabel(provider){if(provider==="google")return"Google";if(provider==="mobile")return"Mobile";return"Email & Password"}
  function showProfile(user){currentUser=user;authView.classList.add("is-hidden");profileView.classList.remove("is-hidden");$("profileName").textContent=(user.name||"Customer").split(" ")[0];$("profileFullName").textContent=user.name||"—";$("profileEmail").textContent=user.email||"—";$("profileEmailStatus").textContent=user.emailVerified?"✓ Verified":"";$("profileProvider").textContent=providerLabel(user.provider);$("profileCreated").textContent=user.createdAt?new Date(user.createdAt+(/Z$/.test(user.createdAt)?"":"Z")).toLocaleDateString():"—";mobileNumber.value=localPhone(user.phone||"");mobileSavedBadge.classList.toggle("is-hidden",!user.phone);message(mobileMessage,user.phone?"Mobile number saved to your account.":"")}
  function showAuth(){currentUser=null;profileView.classList.add("is-hidden");authView.classList.remove("is-hidden");mode("login")}
  function showGoogleResult(){const params=new URLSearchParams(location.search);if(params.get("google")==="error"){const reason=params.get("reason");const text=reason==="google_unavailable"?"Google sign-in is temporarily unavailable. Please use email login or Sign Up.":"Google sign-in could not be completed. Please try again or use email login.";message(authMessage,text,"error");history.replaceState({},document.title,location.pathname)}}
  document.querySelectorAll("[data-password-toggle]").forEach(button=>{button.addEventListener("click",()=>{const input=$(button.dataset.passwordToggle);if(!input)return;const showing=input.type==="text";input.type=showing?"password":"text";button.setAttribute("aria-label",showing?"Show password":"Hide password");button.setAttribute("title",showing?"Show password":"Hide password");button.classList.toggle("is-visible",!showing)})});
  loginTab.addEventListener("click",()=>mode("login"));signupTab.addEventListener("click",()=>mode("signup"));$("forgotPasswordBtn").addEventListener("click",showForgot);$("backToLoginBtn").addEventListener("click",()=>mode("login"));
  loginForm.addEventListener("submit",async e=>{e.preventDefault();message(authMessage,"Signing in…");const form=new FormData(loginForm);try{const data=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:form.get("email"),password:form.get("password")})});if(window.SaiAnalytics)SaiAnalytics.trackLogin();showProfile(data.user)}catch(err){message(authMessage,err.message,"error")}});
  signupForm.addEventListener("submit",async e=>{e.preventDefault();const termsAccepted=$("termsAccepted").checked;if(!termsAccepted){message(authMessage,"Please accept the Terms & Conditions to create your account.","error");return}message(authMessage,"Creating your account…");const form=new FormData(signupForm);try{const data=await api("/api/auth/signup",{method:"POST",body:JSON.stringify({name:form.get("name"),email:form.get("email"),password:form.get("password"),termsAccepted:true})});if(window.SaiAnalytics)SaiAnalytics.trackLogin();showProfile(data.user)}catch(err){message(authMessage,err.message,"error")}});
  forgotForm.addEventListener("submit",async e=>{e.preventDefault();const form=new FormData(forgotForm);message(forgotMessage,"Submitting your reset request…");try{const data=await api("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email:form.get("email")})});message(forgotMessage,data.message||"Password reset request received.","success")}catch(err){message(forgotMessage,err.message,"error")}});
  mobileNumber.addEventListener("input",()=>{mobileNumber.value=mobileNumber.value.replace(/\D/g,"").slice(0,10)});
  mobileForm.addEventListener("submit",async e=>{e.preventDefault();const phone=mobileNumber.value.replace(/\D/g,"");if(!/^[6-9]\d{9}$/.test(phone)){message(mobileMessage,"Enter a valid 10-digit Indian mobile number.","error");return}const button=$("saveMobileBtn");button.disabled=true;button.textContent="Saving…";message(mobileMessage,"Saving mobile number…");try{const data=await api("/api/auth/phone/save",{method:"POST",body:JSON.stringify({phone})});showProfile(data.user);message(mobileMessage,"Mobile number saved successfully.","success")}catch(err){message(mobileMessage,err.message,"error")}finally{button.disabled=false;button.textContent="Save Mobile Number"}});
  $("logoutBtn").addEventListener("click",async()=>{try{await api("/api/auth/logout",{method:"POST",body:"{}"});showAuth();message(authMessage,"You have been logged out.","success")}catch(err){message($("profileMessage"),err.message,"error")}});
  (async()=>{try{const data=await api("/api/auth/me",{method:"GET"});if(data.user)showProfile(data.user);else{showAuth();showGoogleResult()}}catch{showAuth();showGoogleResult()}})();
})();