(function(){"use strict";
const tokenKey="saiShopAdminToken";let token=sessionStorage.getItem(tokenKey)||"";let products=[];
const $=id=>document.getElementById(id);
const loginCard=$("loginCard"),dashboard=$("dashboard"),loginForm=$("loginForm"),loginError=$("loginError"),form=$("productForm"),list=$("productList"),message=$("formMessage");
function authHeaders(json){const h={Authorization:"Bearer "+token};if(json)h["Content-Type"]="application/json";return h}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...authHeaders(Boolean(options.body)),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(response.status===401){logout();throw new Error("Invalid or expired admin token.");}if(!response.ok)throw new Error(data.error||"Request failed.");return data}
function showDashboard(){loginCard.hidden=true;dashboard.hidden=false;loadProducts()}
function logout(){token="";sessionStorage.removeItem(tokenKey);dashboard.hidden=true;loginCard.hidden=false;$("adminToken").value="";loginError.textContent=""}
loginForm.addEventListener("submit",async e=>{e.preventDefault();token=$("adminToken").value.trim();loginError.textContent="";try{await api("/api/admin/products");sessionStorage.setItem(tokenKey,token);showDashboard()}catch(err){loginError.textContent=err.message}})
async function loadProducts(){list.innerHTML='<p class="empty">Loading products…</p>';try{const data=await api("/api/admin/products");products=data.products||[];render()}catch(err){list.innerHTML='<p class="empty">'+escapeHTML(err.message)+'</p>'}}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function money(v){return Number(v)===0?"FREE":"₹"+Number(v).toLocaleString("en-IN")}
function render(){const q=$("productSearch").value.trim().toLowerCase();const shown=products.filter(p=>(p.name+" "+p.category+" "+p.id).toLowerCase().includes(q));$("totalCount").textContent=products.length;$("activeCount").textContent=products.filter(p=>p.active).length;$("freeCount").textContent=products.filter(p=>Number(p.price)===0).length;if(!shown.length){list.innerHTML='<p class="empty">No products found.</p>';return}list.innerHTML=shown.map(p=>'<article class="product-row"><img src="'+escapeHTML((p.images||[])[0]||"Images/favicon.png")+'" alt=""><div><h3>'+escapeHTML(p.name)+'</h3><p>'+escapeHTML(p.category)+' · '+money(p.price)+'</p><span class="badge '+(p.active?"":"hidden")+'">'+(p.active?"Visible":"Hidden")+'</span></div><div class="row-actions"><button class="edit-btn" data-edit="'+escapeHTML(p.id)+'">Edit</button><button class="hide-btn" data-toggle="'+escapeHTML(p.id)+'">'+(p.active?"Hide":"Show")+'</button></div></article>').join("")}
list.addEventListener("click",async e=>{const edit=e.target.closest("[data-edit]"),toggle=e.target.closest("[data-toggle]");if(edit){fill(products.find(p=>p.id===edit.dataset.edit));return}if(toggle){const p=products.find(x=>x.id===toggle.dataset.toggle);if(!p)return;try{await save({...p,active:!p.active});await loadProducts()}catch(err){message.textContent=err.message}}})
function fill(p){if(!p)return;$("formTitle").textContent="Edit Product";$("originalId").value=p.id;$("productId").value=p.id;$("productName").value=p.name;$("productPrice").value=p.price;$("sortOrder").value=p.sort_order||0;$("productCategory").value=p.category;$("productType").value=p.type;$("productFormats").value=(p.formats||[]).join(", ");$("productImages").value=(p.images||[]).join("\n");$("productDescription").value=p.description||"";$("downloadUrl").value=p.downloadUrl||"";$("productActive").checked=Boolean(p.active);form.scrollIntoView({behavior:"smooth",block:"start"})}
function reset(){form.reset();$("originalId").value="";$("productPrice").value="0";$("sortOrder").value="0";$("productActive").checked=true;$("formTitle").textContent="Add Product";message.textContent=""}
function payload(){return{id:$("productId").value.trim(),originalId:$("originalId").value.trim(),name:$("productName").value.trim(),price:Number($("productPrice").value)||0,sort_order:Number($("sortOrder").value)||0,category:$("productCategory").value.trim(),type:$("productType").value.trim(),formats:$("productFormats").value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean),images:$("productImages").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),description:$("productDescription").value.trim(),downloadUrl:$("downloadUrl").value.trim(),active:$("productActive").checked}}
async function save(p){return api("/api/admin/products",{method:"POST",body:JSON.stringify(p)})}
form.addEventListener("submit",async e=>{e.preventDefault();message.textContent="Saving…";try{await save(payload());message.style.color="#047857";message.textContent="Product saved successfully.";reset();await loadProducts()}catch(err){message.style.color="#dc2626";message.textContent=err.message}})
$("resetBtn").addEventListener("click",reset);$("refreshBtn").addEventListener("click",loadProducts);$("logoutBtn").addEventListener("click",logout);$("productSearch").addEventListener("input",render);
if(token)showDashboard();
})();