(() => {
  const frontInput=document.getElementById('mockupFront'),backInput=document.getElementById('mockupBack'),layoutInput=document.getElementById('mockupLayout'),generateBtn=document.getElementById('generateMockup'),downloadBtn=document.getElementById('downloadMockup'),resetBtn=document.getElementById('mockupReset'),message=document.getElementById('mockupMessage'),canvas=document.getElementById('mockupCanvas'),wrap=canvas?.closest('.mockup-preview-wrap');
  if(!canvas||!frontInput||!backInput)return;const ctx=canvas.getContext('2d');
  function loadImage(file){return new Promise((resolve,reject)=>{if(!file)return reject(new Error('missing'));const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('invalid'))};img.src=url})}
  function roundRectPath(c,w,h,r){c.beginPath();c.moveTo(r,0);c.lineTo(w-r,0);c.quadraticCurveTo(w,0,w,r);c.lineTo(w,h-r);c.quadraticCurveTo(w,h,w-r,h);c.lineTo(r,h);c.quadraticCurveTo(0,h,0,h-r);c.lineTo(0,r);c.quadraticCurveTo(0,0,r,0);c.closePath()}
  function drawCard(img,x,y,w,h,angle){ctx.save();ctx.translate(x,y);ctx.rotate(angle*Math.PI/180);ctx.shadowColor='rgba(20,30,40,.22)';ctx.shadowBlur=32;ctx.shadowOffsetY=18;roundRectPath(ctx,w,h,24);ctx.fillStyle='#fff';ctx.fill();ctx.shadowColor='transparent';ctx.clip();const ir=img.width/img.height,tr=w/h;let sx=0,sy=0,sw=img.width,sh=img.height;if(ir>tr){sw=img.height*tr;sx=(img.width-sw)/2}else{sh=img.width/tr;sy=(img.height-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,0,0,w,h);ctx.restore()}
  function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0,s=0,l=(max+min)/2;if(d){s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}return[h*360,s,l]}
  function hslToRgb(h,s,l){h/=360;const hue=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p};let r,g,b;if(!s)r=g=b=l;else{const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;r=hue(p,q,h+1/3);g=hue(p,q,h);b=hue(p,q,h-1/3)}return[Math.round(r*255),Math.round(g*255),Math.round(b*255)]}
  function detectTheme(img){const c=document.createElement('canvas');c.width=80;c.height=80;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,80,80);const data=x.getImageData(0,0,80,80).data,bins=new Map();for(let i=0;i<data.length;i+=16){const r=data[i],g=data[i+1],b=data[i+2],a=data[i+3];if(a<180)continue;const[h,s,l]=rgbToHsl(r,g,b);if(s<.18||l>.93||l<.07)continue;const key=Math.round(h/15)*15;const weight=s*(1-Math.abs(l-.5));bins.set(key,(bins.get(key)||0)+weight)}let hue=210,best=-1;for(const[k,v]of bins)if(v>best){best=v;hue=Number(k)%360}return hue}
  function themeColor(h,s,l){const[r,g,b]=hslToRgb(h,s,l);return`rgb(${r},${g},${b})`}
  function background(front,back){const h1=detectTheme(front),h2=detectTheme(back);let hue=h1;const diff=Math.abs(h1-h2);if(diff<45||diff>315){const a=h1*Math.PI/180,b=h2*Math.PI/180;hue=(Math.atan2(Math.sin(a)+Math.sin(b),Math.cos(a)+Math.cos(b))*180/Math.PI+360)%360}const g=ctx.createLinearGradient(0,0,1200,1200);g.addColorStop(0,themeColor(hue,.62,.94));g.addColorStop(.5,themeColor(hue,.48,.90));g.addColorStop(1,themeColor(hue,.40,.84));ctx.fillStyle=g;ctx.fillRect(0,0,1200,1200);const rg=ctx.createRadialGradient(600,480,80,600,480,820);rg.addColorStop(0,'rgba(255,255,255,.58)');rg.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=rg;ctx.fillRect(0,0,1200,1200)}
  async function generate(){message.textContent='';message.style.color='';if(!frontInput.files[0]||!backInput.files[0]){message.textContent='Please upload both front and back designs.';return}generateBtn.disabled=true;generateBtn.textContent='Generating…';try{const[front,back]=await Promise.all([loadImage(frontInput.files[0]),loadImage(backInput.files[0])]);background(front,back);if(layoutInput.value==='two'){drawCard(back,110,250,760,445,-9);drawCard(front,360,560,760,445,8)}else if(layoutInput.value==='clean'){drawCard(back,90,150,650,380,-8);drawCard(front,470,390,650,380,8);drawCard(back,160,720,650,380,-5)}else{drawCard(front,600,-80,650,380,28);drawCard(back,80,130,650,380,17);drawCard(front,710,420,650,380,24);drawCard(back,170,680,650,380,14);drawCard(front,790,880,650,380,20)}wrap.classList.add('ready');downloadBtn.disabled=false;message.style.color='#047857';message.textContent=layoutInput.options[layoutInput.selectedIndex].text+' mockup generated with an automatic matching background.'}catch(e){message.style.color='#dc2626';message.textContent='Could not read one of the images. Please use JPG, PNG or WebP.'}finally{generateBtn.disabled=false;generateBtn.textContent='Generate Mockup'}}
  generateBtn.addEventListener('click',generate);downloadBtn.addEventListener('click',()=>{const a=document.createElement('a');a.download='sai-graphic-designs-business-card-mockup.png';a.href=canvas.toDataURL('image/png',1);a.click()});resetBtn.addEventListener('click',()=>{frontInput.value='';backInput.value='';layoutInput.value='scatter';ctx.clearRect(0,0,canvas.width,canvas.height);wrap.classList.remove('ready');downloadBtn.disabled=true;message.textContent='';message.style.color=''})
})();