(() => {
  'use strict';
  const syncCore = import('/billing-sync-core.js');
  let syncState = 'Checking sync…', syncing = null, validateBackup;
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money = value => new Intl.NumberFormat('en-IN', {style:'currency',currency:'INR'}).format((Number(value)||0)/100);
  const today = () => new Date().toLocaleDateString('en-CA', {timeZone:'Asia/Kolkata'});
  const id = () => crypto.randomUUID();
  const blank = () => ({version:1, customers:[], catalog:[], invoices:[], payments:[], cash:[], settings:{name:'Sai Graphic Designs',phone:'+91 63811 28781',address:'Madurai, Tamil Nadu',note:'Thank you for your business.'}});
  let db, book = blank(), tab = 'home', busy = false;
  const sections = {home:['Overview','Your business books'],ledger:['Ledger Book','Customer credit & payment history'],cash:['Cash Book','Income & expense logs'],catalog:['Product Catalog','Services, products & pricing'],invoices:['Invoices','Billing, receipts & list'],drafts:['Draft Invoices','Review pending drafts'],bin:['Recycle Bin','Recover deleted records'],settings:['App Settings','Business details & backup']};
  const activeInvoices = () => book.invoices.filter(i => !i.deleted && i.status === 'issued');
  const activePayments = () => book.payments.filter(p => !p.deleted);
  const total = i => i.items.reduce((sum,x)=>sum+Math.round(x.qty*x.rate),0)-i.discount;
  const paid = i => activePayments().filter(p=>p.invoiceId===i.id).reduce((sum,p)=>sum+p.amount,0);
  const balance = c => activeInvoices().filter(i=>i.customerId===c).reduce((sum,i)=>sum+total(i),0)-activePayments().filter(p=>p.customerId===c).reduce((sum,p)=>sum+p.amount,0);
  const customer = cid => book.customers.find(c=>c.id===cid) || {name:'Walk-in Customer',phone:'',address:''};
  function message(value){$('message').textContent=value;}
  function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('sai-billing-book',1);r.onupgradeneeded=()=>r.result.createObjectStore('book');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
  function load(){return new Promise((resolve,reject)=>{const r=db.transaction('book').objectStore('book').get('data');r.onsuccess=()=>{book=r.result||blank();resolve();};r.onerror=()=>reject(r.error);});}
  // Read and mutate inside one transaction so two open tabs never overwrite each other's entries.
  function update(mutator){return new Promise((resolve,reject)=>{const tx=db.transaction('book','readwrite'),store=tx.objectStore('book'),r=store.get('data');let next;r.onsuccess=()=>{try{next=r.result||blank();mutator(next);store.put(next,'data');}catch(e){reject(e);tx.abort();}};tx.oncomplete=()=>{book=next;render();syncState='Saved locally • Waiting to sync';connection();void sync();resolve();};tx.onerror=()=>reject(tx.error);});}
  function cents(value){const number=Number(value);if(!Number.isFinite(number)||number<0||number>1e9)throw new Error('Enter a valid non-negative amount.');return Math.round(number*100);}
  function dateValue(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new Error('Choose a valid date.');return value;}
  function within(date){const p=$('period').value,t=today();if(p==='all')return true;if(p==='today')return date===t;if(p==='month')return date.slice(0,7)===t.slice(0,7);const d=new Date(t+'T00:00:00Z'),day=d.getUTCDay();d.setUTCDate(d.getUTCDate()-(day+6)%7);return date>=d.toISOString().slice(0,10)&&date<=t;}
  const matches = text => String(text).toLowerCase().includes($('search').value.trim().toLowerCase());
  function list(html){return html.length?'<div class="billing-list">'+html.join('')+'</div>':'<div class="empty">No entries yet. Use the button above to add your first entry.</div>';}
  function action(name,label,rid){return `<button type="button" data-action="${name}" data-id="${esc(rid||'')}">${label}</button>`;}
  function card(title,sub,amount,buttons){return `<article class="billing-card"><div class="record-head"><div><h3>${esc(title)}</h3><div class="muted">${esc(sub)}</div></div><strong class="amount">${amount}</strong></div><div class="record-actions">${buttons}</div></article>`;}
  function render(){
    preparedInvoice=null;
    $('stats').innerHTML=[['Total billed',activeInvoices().reduce((s,i)=>s+total(i),0)],['Payments received',activePayments().reduce((s,p)=>s+p.amount,0)],['Customer balance',book.customers.reduce((s,c)=>s+balance(c.id),0)],['Cash balance',activePayments().reduce((s,p)=>s+(p.method==='Cash'?p.amount:0),0)+book.cash.filter(c=>!c.deleted&&c.method==='Cash').reduce((s,c)=>s+(c.type==='income'?c.amount:-c.amount),0)]].map(([label,v])=>`<article><span>${label}</span><strong>${money(v)}</strong></article>`).join('');
    $('tabs').innerHTML=Object.entries(sections).map(([key,[name]])=>`<button data-tab="${key}" aria-current="${key===tab}">${name}</button>`).join('');
    $('toolbar').hidden=['home','settings'].includes(tab);
    $('period').hidden=['ledger','catalog'].includes(tab);
    const add={ledger:['customer','+ Customer'],cash:['cash','+ Cash Entry'],catalog:['catalog','+ Product / Service'],invoices:['invoice','+ Invoice'],drafts:['invoice','+ Draft']};
    $('add').hidden=!add[tab];if(add[tab]){$('add').dataset.action=add[tab][0];$('add').textContent=add[tab][1];}
    let html='';
    if(tab==='home')html='<div class="billing-grid">'+Object.entries(sections).filter(([k])=>k!=='home').map(([key,[name,sub]])=>`<button class="home-card" data-tab="${key}"><span>${({ledger:'♙',cash:'₹',catalog:'▣',invoices:'▤',drafts:'✎',bin:'↺',settings:'⚙'})[key]}</span><b>${name}</b><small>${sub}</small></button>`).join('')+'</div>';
    if(tab==='ledger')html=list(book.customers.filter(c=>!c.deleted&&matches(c.name+' '+c.phone)).map(c=>card(c.name,c.phone+(balance(c.id)<0?' • Customer credit':' • Outstanding balance'),money(balance(c.id)),action('ledger','View Ledger',c.id)+action('payment','Receive Payment',c.id)+action('customer','Edit',c.id)+action('delete:customers','Move to Bin',c.id))));
    if(tab==='catalog')html=list(book.catalog.filter(c=>!c.deleted&&matches(c.name)).map(c=>card(c.name,'Per '+c.unit,money(c.rate),action('catalog','Edit',c.id)+action('delete:catalog','Move to Bin',c.id))));
    if(['invoices','drafts'].includes(tab))html=list(book.invoices.filter(i=>!i.deleted&&i.status===(tab==='drafts'?'draft':'issued')&&within(i.date)&&matches(i.number+' '+i.customer.name+' '+i.items.map(x=>x.name).join(' '))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(i=>card(i.customer.name,`${i.number} • ${i.date} • ${i.items.length} items • ${i.status==='draft'?'Draft':'Paid '+money(paid(i))+' / Due '+money(total(i)-paid(i))}`,money(total(i)),action('view','View / Print',i.id)+(i.status==='draft'?action('invoice','Edit Draft',i.id):action('invoicePayment','Receive Payment',i.id))+action('delete:invoices','Move to Bin',i.id))));
    if(tab==='cash'){
      const rows=[...book.cash.filter(c=>!c.deleted).map(c=>({...c,group:'cash'})),...activePayments().map(p=>({...p,type:'income',note:'Payment from '+customer(p.customerId).name,group:'payments'}))];
      html=list(rows.filter(c=>within(c.date)&&matches(c.note+' '+c.method)).sort((a,b)=>b.date.localeCompare(a.date)).map(c=>card(c.note,`${c.date} • ${c.type} • ${c.method}`,`${c.type==='expense'?'−':'+'}${money(c.amount)}`,c.group==='cash'?action('delete:cash','Move to Bin',c.id):action('delete:payments','Move to Bin',c.id))));
    }
    if(tab==='bin')html=list(['customers','catalog','invoices','payments','cash'].flatMap(group=>book[group].filter(r=>r.deleted&&matches(r.name||r.number||r.note||customer(r.customerId).name)).map(r=>card(r.name||r.number||r.note||'Payment',group,'',action('restore:'+group,'Restore',r.id)))));
    if(tab==='settings')html=`<article class="billing-card"><h2>${esc(book.settings.name)}</h2><p>${esc(book.settings.address)}</p><p>${esc(book.settings.phone)}</p><p>No GST is charged. These are ordinary invoices.</p><div class="settings-actions">${action('settings','Edit Business Details')}${action('backup','Export Backup')}<label>Restore Backup<input id="restoreFile" type="file" accept="application/json,.json" hidden></label>${action('persist','Keep Offline Storage')}</div><p class="muted">Billing records sync securely between your devices while online. Offline changes stay on this device until synced. Open this page on each device to upload its existing records. Keep regular backups. Restore merges entries by ID.</p></article>`;
    $('content').innerHTML=html;
  }
  function field(name,label,value='',type='text',required=true){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'min="0" max="1000000000" step="0.01"':''} maxlength="500"></label>`;}
  function select(name,label,options){return `<label>${label}<select name="${name}">${options}</select></label>`;}
  function option(value,label,selected){return `<option value="${esc(value)}" ${selected?'selected':''}>${esc(label)}</option>`;}
  function method(){return select('method','Payment method',['Cash','UPI','Bank','Card'].map(m=>option(m,m)).join(''));}
  function show(title,html,submit){$('editorTitle').textContent=title;$('fields').innerHTML=html;$('formError').textContent='';$('save').hidden=!submit;$('editForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('save').disabled=true;try{await submit(new FormData(e.target));$('editor').close();message(syncState);}catch(error){$('formError').textContent=error.message;}finally{busy=false;$('save').disabled=false;}};$('editor').showModal();}
  function editCustomer(rid){const c=book.customers.find(c=>c.id===rid);show(c?'Edit Customer':'New Customer',field('name','Customer name',c?.name||'')+field('phone','Mobile',c?.phone||'','tel',false)+field('address','Address',c?.address||'','text',false),async f=>{const name=f.get('name').trim();if(!name)throw new Error('Enter a customer name.');await update(b=>{if(c){Object.assign(b.customers.find(x=>x.id===c.id),{name,phone:f.get('phone').trim(),address:f.get('address').trim()});}else b.customers.push({id:id(),name,phone:f.get('phone').trim(),address:f.get('address').trim(),createdAt:new Date().toISOString()});});});}
  function editCatalog(rid){const c=book.catalog.find(c=>c.id===rid);show(c?'Edit Product / Service':'New Product / Service',field('name','Product / service name',c?.name||'')+field('unit','Unit',c?.unit||'Pcs')+field('rate','Rate (₹)',(c?.rate||0)/100,'number'),async f=>{const name=f.get('name').trim(),rate=cents(f.get('rate')),unit=f.get('unit').trim();if(!name||!unit)throw new Error('Name and unit are required.');await update(b=>{const value={name,unit,rate};if(c)Object.assign(b.catalog.find(x=>x.id===c.id),value);else b.catalog.push({id:id(),...value});});});}
  function itemMarkup(item={name:'',qty:1,unit:'Pcs',rate:0}){return `<div class="item">${field('itemName','Product / service',item.name)}<div class="item-grid">${field('qty','Qty',item.qty,'number')}${field('unit','Unit',item.unit)}${field('rate','Rate (₹)',item.rate/100,'number')}</div><div class="record-head"><span class="lineTotal"></span><button type="button" data-remove-item>Remove</button></div></div>`;}
  function editInvoice(rid){const invoice=book.invoices.find(i=>i.id===rid);if(invoice&&invoice.status!=='draft')throw new Error('Issued invoices cannot be edited.');
    show(invoice?'Edit Draft':'New Invoice',select('customerId','Select customer',option('','Walk-in Customer',!invoice?.customerId)+book.customers.filter(c=>!c.deleted).map(c=>option(c.id,c.name+' '+c.phone,invoice?.customerId===c.id)).join(''))+`<div class="form-grid">${field('date','Invoice date',invoice?.date||today(),'date')}${field('discount','Discount (₹)',(invoice?.discount||0)/100,'number')}</div>`+select('catalogPick','Add from catalog',option('','Choose a service / product')+book.catalog.filter(c=>!c.deleted).map(c=>option(c.id,c.name+' — '+money(c.rate))).join(''))+`<div id="items">${(invoice?.items||[{name:'',qty:1,unit:'Pcs',rate:0}]).map(itemMarkup).join('')}</div><button type="button" id="addItem">+ Custom Item</button><h3 id="invoiceTotal"></h3><div class="form-grid">${field('initialPaid','Payment received now (₹)',0,'number')}${method()}</div>`+field('note','Notes',invoice?.note||'','text',false)+select('status','Save as',option('issued','Issue Invoice',tab!=='drafts')+option('draft','Save Draft',tab==='drafts')),async f=>{
      const cid=f.get('customerId'),items=[...$('items').querySelectorAll('.item')].map(row=>({name:row.querySelector('[name=itemName]').value.trim(),qty:Number(row.querySelector('[name=qty]').value),unit:row.querySelector('[name=unit]').value.trim(),rate:cents(row.querySelector('[name=rate]').value)}));
      if(!items.length||items.some(x=>!x.name||!x.unit||!Number.isFinite(x.qty)||x.qty<=0||x.qty>1e6))throw new Error('Add items with names, units and quantities greater than zero.');
      const discount=cents(f.get('discount')),amount=total({items,discount}),received=cents(f.get('initialPaid')),status=f.get('status'),date=dateValue(f.get('date'));if(amount<0)throw new Error('Discount cannot exceed the subtotal.');if(received>amount)throw new Error('Payment cannot exceed the invoice total.');if(status==='draft'&&received)throw new Error('Drafts cannot receive payments. Issue the invoice first.');
      const iid=invoice?.id||id();await update(b=>{if(cid&&!b.customers.some(c=>c.id===cid&&!c.deleted))throw new Error('Customer unavailable. Reopen this invoice.');const old=b.invoices.find(i=>i.id===iid);if(old&&(old.deleted||old.status!=='draft'))throw new Error('This draft was changed in another tab.');const value={id:iid,number:invoice?.number||'INV-'+iid.slice(0,8).toUpperCase(),customerId:cid,customer:{...customer(cid)},items,discount,date,status,note:f.get('note').trim(),createdAt:invoice?.createdAt||new Date().toISOString()};if(old)Object.assign(old,value);else b.invoices.push(value);if(received)b.payments.push({id:id(),invoiceId:iid,customerId:cid,amount:received,date,method:f.get('method'),note:'Invoice payment'});});
    });
    function recalc(){try{const rows=[...$('items').querySelectorAll('.item')];let subtotal=0;rows.forEach(row=>{const amount=Math.round(Number(row.querySelector('[name=qty]').value)*cents(row.querySelector('[name=rate]').value));row.querySelector('.lineTotal').textContent='Total: '+money(amount);subtotal+=amount;});$('invoiceTotal').textContent='Invoice total: '+money(subtotal-cents($('editForm').elements.discount.value));}catch{} }
    $('addItem').onclick=()=>{$('items').insertAdjacentHTML('beforeend',itemMarkup());recalc();};$('fields').oninput=recalc;$('items').onclick=e=>{if(e.target.hasAttribute('data-remove-item')){e.target.closest('.item').remove();recalc();}};$('editForm').elements.catalogPick.onchange=e=>{const c=book.catalog.find(x=>x.id===e.target.value);if(c){const empty=$('items').querySelector('.item');if(empty&&!empty.querySelector('[name=itemName]').value.trim())empty.remove();$('items').insertAdjacentHTML('beforeend',itemMarkup({...c,qty:1}));e.target.value='';recalc();}};recalc();
  }
  function receive(cid,iid){const i=book.invoices.find(x=>x.id===iid);show('Receive Payment',`<p>${esc(i?i.number+' • '+i.customer.name:customer(cid).name)}</p>`+field('amount','Amount (₹)',i?Math.max(0,total(i)-paid(i))/100:'','number')+field('date','Payment date',today(),'date')+method()+field('note','Notes','','text',false),async f=>{const amount=cents(f.get('amount'));if(!amount)throw new Error('Enter an amount greater than zero.');const date=dateValue(f.get('date'));await update(b=>{if(iid){const bill=b.invoices.find(x=>x.id===iid&&!x.deleted&&x.status==='issued');if(!bill)throw new Error('Invoice unavailable.');const payments=b.payments.filter(p=>!p.deleted&&p.invoiceId===iid).reduce((s,p)=>s+p.amount,0);if(amount>total(bill)-payments)throw new Error('Payment exceeds the invoice balance.');}else if(!b.customers.some(c=>c.id===cid&&!c.deleted))throw new Error('Customer unavailable.');b.payments.push({id:id(),customerId:cid,invoiceId:iid||'',amount,date,method:f.get('method'),note:f.get('note').trim()});});});}
  function cashEntry(){show('Cash Book Entry',select('type','Entry type',option('income','Income')+option('expense','Expense'))+field('note','Description')+field('amount','Amount (₹)','','number')+field('date','Date',today(),'date')+method(),async f=>{const amount=cents(f.get('amount'));if(!amount)throw new Error('Amount must be greater than zero.');const date=dateValue(f.get('date'));await update(b=>b.cash.push({id:id(),type:f.get('type'),amount,date,method:f.get('method'),note:f.get('note').trim()}));});}
  function ledger(cid){const c=customer(cid),rows=[...activeInvoices().filter(i=>i.customerId===cid).map(i=>({date:i.date,text:i.number,amount:total(i)})),...activePayments().filter(p=>p.customerId===cid).map(p=>({date:p.date,text:'Payment • '+p.method+(p.note?' • '+p.note:''),amount:-p.amount,id:p.id}))].sort((a,b)=>a.date.localeCompare(b.date));let running=0;show(c.name+' — Ledger',`<p>${esc(c.phone)} • Balance: <strong>${money(balance(cid))}</strong></p>`+rows.map(r=>{running+=r.amount;return `<div class="ledger-line"><b>${esc(r.date)} • ${esc(r.text)}</b><p>${r.amount<0?'Received':'Billed'}: ${money(Math.abs(r.amount))} • Balance: ${money(running)}</p>${r.id?action('delete:payments','Move Payment to Bin',r.id):''}</div>`;}).join(''),null);}
  function invoiceHtml(i){
    const s=book.settings,receipts=activePayments().filter(p=>p.invoiceId===i.id),methods=[...new Set(receipts.map(p=>p.method))].join(', ')||'Not recorded';
    const previous=i.customerId?balance(i.customerId)-total(i)+paid(i):0;
    const fmt=n=>money(n),date=new Date(i.date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
    return `<article class="invoice-paper"><header class="inv-header"><div class="inv-brand"><img class="inv-logo" src="/Images/home-logo.webp" alt="Sai Graphic Designs logo" width="82" height="102"><div><p class="inv-eyebrow">DESIGN • PRINT • CREATE</p><h1>${esc(s.name)}</h1><p class="inv-business-address">${esc(s.address)}</p>${s.phone?'<p class="inv-business-phone">'+esc(s.phone)+'</p>':''}</div></div><div class="inv-header-note">CREATIVE WORK.<br>PROFESSIONAL BILLING.</div></header><div class="inv-title-band"><span class="inv-title-label">BILLING STATEMENT</span><h2>${i.status==='draft'?'DRAFT INVOICE':'INVOICE'}</h2></div><div class="inv-meta"><section><h3>INVOICE TO</h3><b class="inv-customer">${esc(i.customer.name)}</b>${i.customer.phone?'<p>'+esc(i.customer.phone)+'</p>':''}${i.customer.address?'<p>'+esc(i.customer.address)+'</p>':''}</section><section class="inv-document-meta"><p><span>Invoice No.</span><b>${esc(i.number)}</b></p><p><span>Issue Date</span><b>${esc(date)}</b></p><p><span>Payment</span><b>${esc(methods)}</b></p></section></div><table class="inv-table"><thead><tr><th>NO.</th><th>ITEM / DESCRIPTION</th><th>QTY</th><th>UNIT</th><th>RATE</th><th>AMOUNT</th></tr></thead><tbody>${i.items.map((x,n)=>`<tr><td>${String(n+1).padStart(2,'0')}</td><td><b>${esc(x.name)}</b></td><td>${x.qty.toFixed(1)}</td><td>${esc(x.unit)}</td><td>${fmt(x.rate)}</td><td><b>${fmt(Math.round(x.qty*x.rate))}</b></td></tr>`).join('')}${i.items.length<5?'<tr class="inv-spacer" aria-hidden="true"><td colspan="6" style="height:'+((5-i.items.length)*36)+'px"></td></tr>':''}</tbody><tfoot><tr><td colspan="6">${i.items.length} ${i.items.length===1?'item':'items'} <span> / </span> ${i.items.reduce((n,x)=>n+x.qty,0).toFixed(1)} total quantity <span> / </span> All amounts in INR</td></tr></tfoot></table><div class="inv-settlement"><section class="inv-message"><h3>THANK YOU FOR YOUR BUSINESS</h3><p>${esc(s.note)}</p>${i.note?'<div class="inv-note"><h3>INVOICE NOTES</h3><p>'+esc(i.note)+'</p></div>':''}<p class="inv-tax-note">Ordinary invoice • No GST charged.</p></section><div class="inv-totals"><p><span>Subtotal</span><b>${fmt(total(i)+i.discount)}</b></p>${i.discount?'<p><span>Discount</span><b>− '+fmt(i.discount)+'</b></p>':''}<p class="inv-total"><span>INVOICE TOTAL</span><b>${fmt(total(i))}</b></p><p><span>Amount paid</span><b>${fmt(paid(i))}</b></p><p class="inv-balance"><span>${i.status==='draft'?'Draft amount':'BALANCE DUE'}</span><b>${fmt(total(i)-paid(i))}</b></p></div></div><section class="inv-account"><h3>CUSTOMER ACCOUNT SUMMARY</h3><div><span>Previous balance <b>${fmt(previous)}</b></span><span>Current ledger balance <b>${fmt(i.customerId?balance(i.customerId):total(i)-paid(i))}</b></span></div><small>Account balances reflect current saved records.</small></section><footer class="inv-footer"><div><b>${esc(s.name)}</b><p>${esc(s.phone||s.address)}</p></div><div class="inv-signature"><span></span><p>Authorised signatory</p></div></footer></article>`;
  }
  let preparedInvoice=null;
  function viewInvoice(iid){const i=book.invoices.find(x=>x.id===iid);preparedInvoice=null;show('Invoice Preview','<div class="invoice-preview">'+invoiceHtml(i)+'</div><div class="record-actions">'+action('downloadInvoice','Download PDF',iid)+action('shareInvoice','Share PDF',iid)+action('whatsappInvoice','WhatsApp',iid)+action('print','Print / Save PDF',iid)+'</div><p class="muted">Share PDF opens your device share menu. Choose WhatsApp if available. On desktop, WhatsApp downloads the PDF first; attach it in the chat.</p>',null);}
  async function invoiceFile(iid){
    if(preparedInvoice?.id===iid)return preparedInvoice.file;
    if(!window.html2canvas||!window.jspdf)throw new Error('PDF tools unavailable. Reload this page online once to prepare offline downloads.');
    const host=document.createElement('div');host.className='invoice-export';host.innerHTML=invoiceHtml(book.invoices.find(i=>i.id===iid));document.body.appendChild(host);
    try{await Promise.all([...host.querySelectorAll('img')].map(img=>img.decode()));const canvas=await html2canvas(host.firstElementChild,{scale:2,backgroundColor:'#ffffff',logging:false});const {jsPDF}=window.jspdf,pdf=new jsPDF({unit:'mm',format:'a4'}),pageHeight=277,width=190,pixelsPerMM=canvas.width/width,maxHeight=Math.floor(pageHeight*pixelsPerMM);
      // End PDF pages between table rows or blocks so invoice text is not cut in half.
      const rect=host.firstElementChild.getBoundingClientRect(),breaks=[...host.querySelectorAll('tr,.inv-totals p,.inv-account,.inv-note,.inv-footer')].map(el=>Math.round((el.getBoundingClientRect().bottom-rect.top)*2)).filter(y=>y>0).sort((a,b)=>a-b);
      let top=0,page=0;while(top<canvas.height){let bottom=Math.min(top+maxHeight,canvas.height);if(bottom<canvas.height){const safe=breaks.filter(y=>y>top+maxHeight*.4&&y<=bottom).at(-1);if(safe)bottom=safe;}const slice=document.createElement('canvas');slice.width=canvas.width;slice.height=bottom-top;slice.getContext('2d').drawImage(canvas,0,top,canvas.width,slice.height,0,0,canvas.width,slice.height);if(page++)pdf.addPage();pdf.addImage(slice.toDataURL('image/png'),'PNG',10,10,width,slice.height/pixelsPerMM);top=bottom;}
      const file=new File([pdf.output('blob')],book.invoices.find(i=>i.id===iid).number+'.pdf',{type:'application/pdf'});preparedInvoice={id:iid,file};return file;
    }finally{host.remove();}
  }
  function downloadFile(file){const url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  async function shareInvoice(iid,mode){
    const buttons=[...$('fields').querySelectorAll('[data-action]')];buttons.forEach(b=>b.disabled=true);
    try{const file=await invoiceFile(iid),i=book.invoices.find(x=>x.id===iid);
      if(mode==='downloadInvoice'){downloadFile(file);message('Invoice PDF downloaded.');return;}
      if(mode==='shareInvoice'&&navigator.canShare?.({files:[file]})&&navigator.share){try{await navigator.share({files:[file],title:i.number,text:'Invoice from '+book.settings.name});return;}catch(e){if(e.name==='AbortError')return;}}
      downloadFile(file);
      if(mode==='whatsappInvoice'){let phone=String(i.customer.phone||'').replace(/\D/g,'');if(phone.length===10)phone='91'+phone;if(phone.length<7||phone.length>15)phone='';const text='Hello '+i.customer.name+',\nInvoice '+i.number+' from '+book.settings.name+'\nTotal: '+money(total(i))+'\nPaid: '+money(paid(i))+'\nBalance: '+money(total(i)-paid(i));const link=document.createElement('a');link.href='https://wa.me/'+phone+'?text='+encodeURIComponent(text);link.target='_blank';link.rel='noopener noreferrer';link.click();message('PDF downloaded. Attach this file in the WhatsApp chat.');}
      else message('File sharing is unavailable in this browser. PDF downloaded; attach it in WhatsApp.');
    }finally{buttons.forEach(b=>b.disabled=false);}
  }
  function settings(){const s=book.settings;show('Business Details',field('name','Business name',s.name)+field('address','Address',s.address,'text',false)+field('phone','Mobile',s.phone,'tel',false)+field('note','Invoice footer',s.note,'text',false),async f=>update(b=>{b.settings={name:f.get('name').trim(),address:f.get('address').trim(),phone:f.get('phone').trim(),note:f.get('note').trim()};}));}
  async function move(group,rid,restore=false){await update(b=>{const r=b[group].find(x=>x.id===rid);if(!r)throw new Error('Record unavailable.');if(group==='customers'&&!restore&&(b.invoices.some(i=>i.customerId===rid&&!i.deleted)||b.payments.some(p=>p.customerId===rid&&!p.deleted)))throw new Error('This customer has billing records. Keep their account for the ledger.');r.deleted=!restore;
    // Linked receipts follow an invoice into the bin, but independently deleted receipts stay deleted on restore.
    if(group==='invoices')b.payments.filter(p=>p.invoiceId===rid).forEach(p=>{if(!restore&&!p.deleted){p.deleted=true;p.deletedWithInvoice=true;}else if(restore&&p.deletedWithInvoice){p.deleted=false;delete p.deletedWithInvoice;}});
    if(group==='payments'&&restore&&r.invoiceId){const i=b.invoices.find(i=>i.id===r.invoiceId);if(!i||i.deleted)throw new Error('Restore the linked invoice first.');const other=b.payments.filter(p=>!p.deleted&&p.invoiceId===r.invoiceId&&p.id!==rid).reduce((s,p)=>s+p.amount,0);if(other+r.amount>total(i))throw new Error('Restoring this payment would overpay the invoice.');} });message(restore?'Record restored.':'Moved to Recycle Bin.');}
  async function backup(){await load();const blob=new Blob([JSON.stringify({format:'sai-billing-backup',exportedAt:new Date().toISOString(),book},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Sai-Billing-Backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Backup exported. Keep the file safe.');}

  async function restore(file){if(file.size>20*1024*1024)throw new Error('Backup exceeds 20 MB.');const incoming=validateBackup(JSON.parse(await file.text()));if(!confirm('Merge this backup into your billing book? Existing records with the same ID will be kept.'))return;await update(b=>{const wasEmpty=!b.invoices.length&&!b.customers.length&&!b.cash.length;for(const g of ['customers','catalog','invoices','payments','cash']){const ids=new Set(b[g].map(r=>r.id));b[g].push(...incoming[g].filter(r=>!ids.has(r.id)));}if(wasEmpty)b.settings=incoming.settings;validateBackup({format:'sai-billing-backup',book:b});});message('Backup merged successfully.');}
  document.addEventListener('click',async e=>{const t=e.target.closest('[data-action],[data-tab]');if(!t)return;try{if(t.dataset.tab){tab=t.dataset.tab;$('search').value='';render();return;}const a=t.dataset.action,rid=t.dataset.id;if(a.startsWith('delete:')||a.startsWith('restore:')){const restore=a.startsWith('restore:');if(!restore&&!confirm('Move this record to the Recycle Bin?'))return;await move(a.split(':')[1],rid,restore);if($('editor').open)$('editor').close();return;}if(a==='customer')editCustomer(rid);if(a==='catalog')editCatalog(rid);if(a==='invoice')editInvoice(rid);if(a==='cash')cashEntry();if(a==='ledger')ledger(rid);if(a==='payment')receive(rid);if(a==='invoicePayment'){const i=book.invoices.find(x=>x.id===rid);receive(i.customerId,i.id);}if(a==='view')viewInvoice(rid);if(['downloadInvoice','shareInvoice','whatsappInvoice'].includes(a))await shareInvoice(rid,a);if(a==='print'){$('printArea').innerHTML=invoiceHtml(book.invoices.find(i=>i.id===rid));window.print();}if(a==='settings')settings();if(a==='backup')await backup();if(a==='persist'){const ok=await navigator.storage?.persist?.();message(ok?'Persistent offline storage enabled. Still keep backups.':'Browser did not grant persistent storage. Keep regular backups.');}}catch(error){message(error.message);}});
  $('closeEditor').onclick=()=>$('editor').close();$('editor').addEventListener('close',()=>{$('fields').oninput=null;});$('search').oninput=render;$('period').onchange=render;document.addEventListener('change',async e=>{if(e.target.id==='restoreFile'&&e.target.files[0]){try{await restore(e.target.files[0]);}catch(error){message('Restore failed: '+error.message);}e.target.value='';}});
  function connection(){ $('connection').textContent=navigator.onLine?syncState:'Offline • Saved on this device • Sync when online'; }
  function snapshot(){return new Promise((resolve,reject)=>{const tx=db.transaction('book'),store=tx.objectStore('book'),a=store.get('data'),b=store.get('sync-base');tx.oncomplete=()=>resolve({local:a.result||blank(),base:b.result||null});tx.onerror=()=>reject(tx.error);});}
  function storeSynced(expected, merged){return new Promise((resolve,reject)=>{const tx=db.transaction('book','readwrite'),store=tx.objectStore('book'),r=store.get('data');let accepted=false;r.onsuccess=()=>{if(JSON.stringify(r.result||blank())!==JSON.stringify(expected))return;store.put(merged,'data');store.put(merged,'sync-base');accepted=true;};tx.oncomplete=()=>{if(accepted){book=merged;if(!$('editor').open)render();}resolve(accepted);};tx.onerror=()=>reject(tx.error);});}
  async function api(method,body){const response=await fetch('/api/admin/billing',{method,cache:'no-store',headers:{'Authorization':'Bearer '+sessionStorage.getItem('saiShopAdminToken'),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(response.status===409)return {conflict:true};if(!response.ok)throw new Error(data.error||'Billing sync unavailable.');return data;}
  function sync(){if(!db||!navigator.onLine)return Promise.resolve();if(syncing)return syncing;syncing=(async()=>{try{syncState='Syncing…';connection();const {mergeBooks}=await syncCore;for(let attempt=0;attempt<8;attempt++){const state=await snapshot(),remote=await api('GET');const merged=mergeBooks(state.base,state.local,remote.book||blank());if(JSON.stringify(merged)!==JSON.stringify(remote.book)){const saved=await api('PUT',{revision:remote.revision,book:merged});if(saved.conflict)continue;}if(!await storeSynced(state.local,merged))continue;syncState='Synced • Available on mobile & desktop';connection();return;}throw new Error('Book is changing on another device. Sync will retry.');}catch(error){syncState='Not synced • '+error.message;connection();message(syncState+' Your local records are retained.');}finally{syncing=null;}})();return syncing;}
  window.addEventListener('online',()=>{connection();void sync();});window.addEventListener('offline',connection);
  window.addEventListener('focus',async()=>{if(db&&!$('editor').open){await load();render();void sync();}});
  setInterval(()=>{if(db&&document.visibilityState==='visible'&&!busy&&!$('editor').open)void sync();},15000);
  async function start(){if(!sessionStorage.getItem('saiShopAdminToken'))return;try{({validateBackup}=await syncCore);db=await openDB();await load();$('locked').hidden=true;$('app').hidden=false;render();connection();await sync();if('serviceWorker' in navigator){await navigator.serviceWorker.register('/billing-sw.js');await navigator.serviceWorker.ready;}}catch(error){message('Could not open billing: '+error.message);}}
  start();
})();
