import assert from 'node:assert/strict';
import {handleAssistant} from '../src/assistant.js';
import worker from '../src/index.js';
let calls=0,quota=1,output={reply:'You have two products.',action:'none',text:'',taskNumber:0};
const products=[{id:'a',name:'Card',category:'Print',price:0,active:true,clicks:8,downloadUrl:'private-download-link'},{id:'b',name:'Box',category:'Pack',price:99,active:false,clicks:2,downloadUrl:''}];
const DB={prepare(){return {run:async()=>({}),bind(){return this},first:async()=>({count:quota})}}};
const env={DB,ADMIN_TOKEN:'test-admin',GEMINI_API_KEY:'test-secret'};
const request=(body={message:'How is my shop doing?'},auth=true)=>new Request('https://example.test/api/admin/assistant',{method:'POST',headers:{'content-type':'application/json',...(auth?{authorization:'Bearer test-admin'}:{})},body:JSON.stringify(body)});
globalThis.fetch=async(url,options)=>{calls++;if(url.includes('/models?'))return Response.json({models:[{name:'models/gemini-2.5-flash',supportedGenerationMethods:['generateContent']},{name:'models/gemini-9.0-flash-image',supportedGenerationMethods:['generateContent']}]});assert.match(url,/generativelanguage.googleapis.com/);assert.equal(options.headers['x-goog-api-key'],'test-secret');assert.ok(!options.body.includes('test-secret'));assert.ok(!options.body.includes('private-download-link'));const body=JSON.parse(options.body);assert.equal(body.generationConfig.responseMimeType,'application/json');assert.ok(body.generationConfig.responseJsonSchema);assert.ok(!body.generationConfig.responseFormat);assert.match(url,/models\/gemini-2.5-flash:generateContent$/);const context=JSON.parse(body.contents[0].parts[0].text);assert.equal(context.SHOP_DATA.totalProducts,2);assert.equal(context.SHOP_DATA.totalRecordedProductClicks,10);return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(output)}]}}]});};
assert.equal((await worker.fetch(request({},false),env)).status,401);assert.equal(calls,0);
assert.equal((await handleAssistant(request(),{...env,GEMINI_API_KEY:''},()=>products)).status,503);assert.equal(calls,0);
assert.equal((await handleAssistant(request({message:'x'.repeat(1001)}),env,()=>products)).status,400);
assert.equal((await handleAssistant(request({message:'x',junk:'x'.repeat(70000)}),env,()=>products)).status,400);
assert.equal((await handleAssistant(request(),env,()=>products)).status,200);
output={reply:'I will add it.',action:'add_task',text:'Call customer',taskNumber:0};assert.equal((await (await handleAssistant(request({message:'Add a task to call customer'}),env,()=>products)).json()).action,'add_task');
output={reply:'Deleted.',action:'delete_product',text:'a',taskNumber:0};assert.equal((await handleAssistant(request(),env,()=>products)).status,502);
output={reply:'Done.',action:'complete_task',text:'',taskNumber:12};assert.equal((await handleAssistant(request({message:'Complete task',tasks:[{text:'Call',done:false}]}),env,()=>products)).status,400);
quota=21;const before=calls;assert.equal((await handleAssistant(request(),env,()=>products)).status,429);assert.equal(calls,before);quota=1;
globalThis.fetch=async()=>new Response('upstream-secret-error',{status:403});const error=await handleAssistant(request(),env,()=>products);assert.equal(error.status,502);assert.ok(!(await error.text()).includes('upstream-secret-error'));
console.log('PASS: authorization, missing key, request bounds, grounded snapshot, private-link exclusion, allowed actions, rejected mutation, task bounds, rate limit, safe upstream errors.');

globalThis.fetch=async()=>Response.json({models:[{name:'models/gemini-9.0-flash-image',supportedGenerationMethods:['generateContent']}]});
assert.equal((await (await handleAssistant(request(),env,()=>products)).json()).code,'GEMINI_NO_TEXT_MODEL');
globalThis.fetch=async()=>Response.json({error:{message:'secret-do-not-return',details:[{reason:'API_KEY_INVALID'}]}},{status:400});
const invalid=await (await handleAssistant(request(),env,()=>products)).json();assert.match(invalid.error,/invalid or expired/);assert.equal(invalid.code,'GEMINI_HTTP_400');assert.ok(!JSON.stringify(invalid).includes('secret-do-not-return'));
console.log('PASS: automatic text-model selection, image exclusion, compatible JSON fields, unavailable model, categorized key errors.');
