import baseWorker from "./worker.js";
const RETENTION_DAYS=Number.isFinite(Number(globalThis.ANALYTICS_RETENTION_DAYS))?Number(globalThis.ANALYTICS_RETENTION_DAYS):90;
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff",...extra}})}
function authorized(request,env){const token=env.ADMIN_TOKEN||"",v=request.headers.get("authorization")||"",s=v.startsWith("Bearer ")?v.slice(7):"";if(!token||s.length!==token.length)return false;let d=0;for(let i=0;i<token.length;i++)d|=token.charCodeAt(i)^s.charCodeAt(i);return d===0}
function cookie(request,name){const raw=request.headers.get("cookie")||"";for(const part of raw.split(";")){const p=part.trim(),i=p.indexOf("=");if(i>0&&p.slice(0,i)===name)return p.slice(i+1)}return""}
async function hash(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));let b="";for(const x of new Uint8Array(d))b+=String.fromCharCode(x);return btoa(b)}
async function ensureAnalytics(env){await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_accounts (id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT UNIQUE,password_hash TEXT,password_salt TEXT,google_sub TEXT UNIQUE,auth_provider TEXT NOT NULL DEFAULT 'email',email_verified INTEGER NOT NULL DEFAULT 0,phone_verified INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,terms_accepted_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_login_at TEXT)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_account_sessions (token_hash TEXT PRIMARY KEY,customer_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at TEXT NOT NULL)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS website_visitors (visitor_id TEXT PRIMARY KEY,first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,visit_count INTEGER NOT NULL DEFAULT 0)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS website_sessions (session_id TEXT PRIMARY KEY,visitor_id TEXT NOT NULL,customer_id TEXT,started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,ended_at TEXT)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS website_events (id INTEGER PRIMARY KEY AUTOINCREMENT,visitor_id TEXT NOT NULL,session_id TEXT NOT NULL,customer_id TEXT,event_type TEXT NOT NULL,path TEXT,referrer TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_analytics (customer_id TEXT PRIMARY KEY,login_count INTEGER NOT NULL DEFAULT 0,website_opens INTEGER NOT NULL DEFAULT 0,last_open_at TEXT,last_active_at TEXT)`),
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS analytics_settings (id INTEGER PRIMARY KEY CHECK(id=1),retention_days INTEGER NOT NULL DEFAULT 90,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 env.DB.prepare(`INSERT OR IGNORE INTO analytics_settings(id,retention_days) VALUES(1,90)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_website_events_customer ON website_events(customer_id,created_at)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_website_events_visitor ON website_events(visitor_id,created_at)`),
 env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_website_sessions_customer ON website_sessions(customer_id,last_seen_at)`)
])}
async function retentionDays(env){await ensureAnalytics(env);const r=await env.DB.prepare("SELECT retention_days FROM analytics_settings WHERE id=1").first();return Math.max(7,Math.min(730,Number(r?.retention_days)||90))}
async function cleanupAnalytics(env){const days=await retentionDays(env);await env.DB.batch([
 env.DB.prepare("DELETE FROM website_events WHERE created_at < datetime('now', ?)").bind(`-${days} days`),
 env.DB.prepare("DELETE FROM website_sessions WHERE last_seen_at < datetime('now', ?)").bind(`-${days} days`),
 env.DB.prepare("DELETE FROM website_visitors WHERE last_seen_at < datetime('now', ?)").bind(`-${days} days`)
]);return days}
async function currentCustomer(request,env){const raw=cookie(request,"sai_customer_session");if(!raw)return null;const h=await hash(raw);return env.DB.prepare(`SELECT c.id,c.name,c.email FROM customer_account_sessions s JOIN customer_accounts c ON c.id=s.customer_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND c.active=1 LIMIT 1`).bind(h).first()}
async function analyticsEvent(request,env){await ensureAnalytics(env);let x;try{x=await request.json()}catch{return json({error:"Invalid JSON."},400)}const visitorId=String(x.visitorId||"").slice(0,100),sessionId=String(x.sessionId||"").slice(0,100),type=String(x.type||"event").slice(0,40),path=String(x.path||"/").slice(0,500),referrer=String(x.referrer||"").slice(0,1000);if(!visitorId||!sessionId)return json({error:"Missing visitor or session ID."},400);const customer=await currentCustomer(request,env),customerId=customer?.id||null;const existing=await env.DB.prepare("SELECT session_id FROM website_sessions WHERE session_id=? LIMIT 1").bind(sessionId).first(),isNew=!existing;await env.DB.prepare(`INSERT INTO website_visitors(visitor_id,last_seen_at,visit_count) VALUES(?,CURRENT_TIMESTAMP,?) ON CONFLICT(visitor_id) DO UPDATE SET last_seen_at=CURRENT_TIMESTAMP,visit_count=website_visitors.visit_count+excluded.visit_count`).bind(visitorId,isNew?1:0).run();await env.DB.prepare(`INSERT INTO website_sessions(session_id,visitor_id,customer_id,started_at,last_seen_at) VALUES(?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(session_id) DO UPDATE SET customer_id=COALESCE(website_sessions.customer_id,excluded.customer_id),last_seen_at=CURRENT_TIMESTAMP`).bind(sessionId,visitorId,customerId).run();await env.DB.prepare("INSERT INTO website_events(visitor_id,session_id,customer_id,event_type,path,referrer) VALUES(?,?,?,?,?,?)").bind(visitorId,sessionId,customerId,type,path,referrer).run();if(customerId){await env.DB.prepare(`INSERT INTO customer_analytics(customer_id,last_active_at) VALUES(?,CURRENT_TIMESTAMP) ON CONFLICT(customer_id) DO UPDATE SET last_active_at=CURRENT_TIMESTAMP`).bind(customerId).run();if(type==="login")await env.DB.prepare("UPDATE customer_analytics SET login_count=login_count+1,website_opens=website_opens+1,last_open_at=CURRENT_TIMESTAMP,last_active_at=CURRENT_TIMESTAMP WHERE customer_id=?").bind(customerId).run();else if(isNew&&type==="page_open")await env.DB.prepare("UPDATE customer_analytics SET website_opens=website_opens+1,last_open_at=CURRENT_TIMESTAMP,last_active_at=CURRENT_TIMESTAMP WHERE customer_id=?").bind(customerId).run()}if(type==="session_end")await env.DB.prepare("UPDATE website_sessions SET ended_at=CURRENT_TIMESTAMP,last_seen_at=CURRENT_TIMESTAMP WHERE session_id=?").bind(sessionId).run();return json({success:true})}
async function adminCustomers(request,env){if(!authorized(request,env))return json({error:"Unauthorized."},401);await ensureAnalytics(env);const r=await env.DB.prepare(`SELECT c.id,c.name,c.email,c.phone,c.auth_provider,c.active,c.created_at,c.last_login_at,COALESCE(a.login_count,0) login_count,COALESCE(a.website_opens,0) website_opens,a.last_open_at,a.last_active_at,EXISTS(SELECT 1 FROM customer_account_sessions s WHERE s.customer_id=c.id AND s.expires_at>CURRENT_TIMESTAMP) logged_in FROM customer_accounts c LEFT JOIN customer_analytics a ON a.customer_id=c.id ORDER BY COALESCE(a.last_active_at,c.last_login_at,c.created_at) DESC`).all();const customers=(r.results||[]).map(c=>({id:c.id,name:c.name,email:c.email||"",phone:c.phone||"",provider:c.auth_provider||"email",active:Boolean(c.active),createdAt:c.created_at,lastLoginAt:c.last_login_at||"",loginCount:Number(c.login_count)||0,websiteOpens:Number(c.website_opens)||0,lastOpenAt:c.last_open_at||"",lastActiveAt:c.last_active_at||"",loggedIn:Boolean(c.logged_in)}));return json({customers,total:customers.length,active:customers.filter(c=>c.active).length,currentlyOnline:customers.filter(c=>c.loggedIn).length,totalLogins:customers.reduce((n,c)=>n+c.loginCount,0),totalWebsiteOpens:customers.reduce((n,c)=>n+c.websiteOpens,0),retentionDays:await retentionDays(env)})}
async function adminOverview(request,env){if(!authorized(request,env))return json({error:"Unauthorized."},401);await ensureAnalytics(env);const[v,s,e,c]=await Promise.all([env.DB.prepare("SELECT COUNT(*) total,COALESCE(SUM(visit_count),0) visits FROM website_visitors").first(),env.DB.prepare("SELECT COUNT(*) total FROM website_sessions WHERE last_seen_at>datetime('now','-5 minutes')").first(),env.DB.prepare("SELECT COUNT(*) total FROM website_events WHERE event_type='page_open'").first(),env.DB.prepare("SELECT COUNT(*) total FROM customer_accounts WHERE active=1").first()]);return json({uniqueVisitors:Number(v?.total)||0,totalVisits:Number(v?.visits)||0,activeSessions:Number(s?.total)||0,totalPageOpens:Number(e?.total)||0,totalCustomers:Number(c?.total)||0,retentionDays:await retentionDays(env)})}
async function adminPrivacy(request,env){if(!authorized(request,env))return json({error:"Unauthorized."},401);const current=await retentionDays(env);if(request.method==="GET")return json({retentionDays:current,minDays:7,maxDays:730,storedData:["Customer account name, email and optional mobile number","Hashed password credentials (never plaintext passwords)","Login count and last login timestamp","Pseudonymous visitor and session IDs","Visit/session counts and timestamps","Page path and referrer for analytics events","Customer website-open count and last active timestamp"],notStored:["Plaintext passwords","Payment card data","Exact GPS location","Private message contents","Analytics IP address storage"]});let body={};try{body=await request.json()}catch{return json({error:"Invalid JSON."},400)}const days=Math.max(7,Math.min(730,Number(body.retentionDays)||90));await env.DB.prepare("UPDATE analytics_settings SET retention_days=?,updated_at=CURRENT_TIMESTAMP WHERE id=1").bind(days).run();await cleanupAnalytics(env);return json({success:true,retentionDays:days})}
export default{async fetch(request,env,ctx){const u=new URL(request.url);try{if(u.pathname==="/api/analytics/event"&&request.method==="POST")return await analyticsEvent(request,env);if(u.pathname==="/api/admin/customer-analytics"&&request.method==="GET")return await adminCustomers(request,env);if(u.pathname==="/api/admin/analytics/overview"&&request.method==="GET")return await adminOverview(request,env);if(u.pathname==="/api/admin/privacy"&&(request.method==="GET"||request.method==="POST"))return await adminPrivacy(request,env);if(u.pathname==="/api/admin/analytics/cleanup"&&request.method==="POST"){if(!authorized(request,env))return json({error:"Unauthorized."},401);return json({success:true,retentionDays:await cleanupAnalytics(env)})}}catch(e){console.error("Analytics error:",e);return json({error:"Analytics service temporarily unavailable."},500)}const response=await baseWorker.fetch(request,env,ctx),type=response.headers.get("content-type")||"";if(!type.includes("text/html")||u.pathname.startsWith("/admin"))return response;return new HTMLRewriter().on("head",{element(el){el.append('<script src="/analytics.js" defer></script>',{html:true})}}).transform(response)}};